OPTION: "jointmaps_rgb_bodyparts"
PRETRAINED: True
COPY_RGB_WEIGHTS: True
TARGET_SIZE: [112, 112]
BODYPARTS_DIR: "bodyparts_binary"
AUGMENTATIONS: [hflip, crop]
STRATIFIED: True  # feeding more touch class (underrepresented) to balance
LOSS_WEIGHTS: [1, 1]  # keep these the same if stratified is True
LR: 0.001
BATCH_SIZE: 64
EPOCHS: 10
TRAIN_FRAC : 0.3