OPTION: "jointmaps_rgb_bodyparts"
PRETRAINED: False
COPY_RGB_WEIGHTS: False
TARGET_SIZE: [112, 112]
BODYPARTS_DIR: "bodyparts_binary"
DEPTHMAPS_DIR: "depth_maps"
AUGMENTATIONS: [hflip, crop, color]
STRATIFIED: True  # feeding more touch class (underrepresented) to balance
LOSS_WEIGHTS: [1, 1]  # keep these the same if stratified is True
LR: 0.001
BATCH_SIZE: 64
EPOCHS: 20